version: '3.8'

services:
  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    env_file: 
      - .env
    depends_on:
      - api
      - postgres

  api:
    build:
      context: ./api
    ports:
      - "4000:4000"
    env_file: 
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
