import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/shared/ui/sonner";
import "./globals.css";
import QueryProvider from "@/shared/providers/query-provider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <Toaster />
          <main className="flex flex-col min-h-screen">{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
